{"timestamp": "2025-08-12T11:35:47.695532", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T11:35:57.587298", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T11:39:20.120263", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T11:39:39.526178", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T11:39:41.581302", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T11:39:43.671331", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T11:39:45.844254", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T11:40:02.052865", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T11:44:03.970740", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T11:44:07.776198", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T12:18:55.136407", "level": "WARNING", "logger": "django.request", "message": "Method Not Allowed (POST): /api/auth/token/", "module": "log", "function": "log_response", "line": 253}
{"timestamp": "2025-08-12T12:21:44.549031", "level": "WARNING", "logger": "django.request", "message": "Bad Request: /api/v1/token/", "module": "log", "function": "log_response", "line": 253}
{"timestamp": "2025-08-12T12:27:07.565323", "level": "WARNING", "logger": "django.request", "message": "Unauthorized: /api/v1/auth/me/", "module": "log", "function": "log_response", "line": 253}
{"timestamp": "2025-08-12T12:28:52.299109", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T12:28:55.549879", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T12:29:21.004875", "level": "WARNING", "logger": "django.request", "message": "Unauthorized: /api/v1/auth/me/", "module": "log", "function": "log_response", "line": 253}
{"timestamp": "2025-08-12T12:31:09.732911", "level": "WARNING", "logger": "django.request", "message": "Unauthorized: /api/v1/auth/me/", "module": "log", "function": "log_response", "line": 253}
{"timestamp": "2025-08-12T14:04:08.576470", "level": "WARNING", "logger": "django.request", "message": "Method Not Allowed (PATCH): /api/accounts/me/", "module": "log", "function": "log_response", "line": 253}
{"timestamp": "2025-08-12T14:05:05.078776", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T14:15:26.574325", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T14:15:31.162586", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T14:18:08.851044", "level": "WARNING", "logger": "django.request", "message": "Method Not Allowed (PATCH): /api/accounts/me/", "module": "log", "function": "log_response", "line": 253}
{"timestamp": "2025-08-12T14:23:03.413232", "level": "WARNING", "logger": "django.request", "message": "Method Not Allowed (PATCH): /api/accounts/me/", "module": "log", "function": "log_response", "line": 253}
{"timestamp": "2025-08-12T14:28:41.971973", "level": "WARNING", "logger": "django.request", "message": "Method Not Allowed (PATCH): /api/accounts/me/", "module": "log", "function": "log_response", "line": 253}
{"timestamp": "2025-08-12T14:39:30.520151", "level": "WARNING", "logger": "django.request", "message": "Method Not Allowed (PATCH): /api/accounts/me/", "module": "log", "function": "log_response", "line": 253}
{"timestamp": "2025-08-12T16:40:32.235913", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
