{"timestamp": "2025-08-12T11:35:47.679886", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T11:35:57.557476", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T11:35:57.598012", "level": "ERROR", "logger": "django.server", "message": "\"GET /api/v1/schema/ HTTP/1.1\" 500 164136", "module": "basehttp", "function": "log_message", "line": 213}
{"timestamp": "2025-08-12T11:39:20.064623", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T11:39:20.128395", "level": "ERROR", "logger": "django.server", "message": "\"GET /api/v1/schema/ HTTP/1.1\" 500 145", "module": "basehttp", "function": "log_message", "line": 213}
{"timestamp": "2025-08-12T11:39:39.511661", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T11:39:39.544018", "level": "ERROR", "logger": "django.server", "message": "\"GET /api/v1/schema/ HTTP/1.1\" 500 145", "module": "basehttp", "function": "log_message", "line": 213}
{"timestamp": "2025-08-12T11:39:41.566478", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T11:39:41.591384", "level": "ERROR", "logger": "django.server", "message": "\"GET /api/v1/schema/ HTTP/1.1\" 500 145", "module": "basehttp", "function": "log_message", "line": 213}
{"timestamp": "2025-08-12T11:39:43.634982", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T11:39:43.691116", "level": "ERROR", "logger": "django.server", "message": "\"GET /api/v1/schema/ HTTP/1.1\" 500 145", "module": "basehttp", "function": "log_message", "line": 213}
{"timestamp": "2025-08-12T11:39:45.807458", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T11:39:45.855250", "level": "ERROR", "logger": "django.server", "message": "\"GET /api/v1/schema/ HTTP/1.1\" 500 145", "module": "basehttp", "function": "log_message", "line": 213}
{"timestamp": "2025-08-12T11:40:02.035230", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T11:40:02.053891", "level": "ERROR", "logger": "django.server", "message": "\"GET /api/v1/schema/ HTTP/1.1\" 500 145", "module": "basehttp", "function": "log_message", "line": 213}
{"timestamp": "2025-08-12T11:44:03.909475", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T11:44:03.983757", "level": "ERROR", "logger": "django.server", "message": "\"GET /api/v1/schema/ HTTP/1.1\" 500 145", "module": "basehttp", "function": "log_message", "line": 213}
{"timestamp": "2025-08-12T11:44:07.756092", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T11:44:07.782920", "level": "ERROR", "logger": "django.server", "message": "\"GET /api/v1/schema/ HTTP/1.1\" 500 145", "module": "basehttp", "function": "log_message", "line": 213}
{"timestamp": "2025-08-12T12:28:52.287850", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T12:28:52.842787", "level": "ERROR", "logger": "django.server", "message": "\"GET /api/v1/schema/ HTTP/1.1\" 500 145", "module": "basehttp", "function": "log_message", "line": 213}
{"timestamp": "2025-08-12T12:28:55.504294", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T12:28:55.766594", "level": "ERROR", "logger": "django.server", "message": "\"GET /api/v1/schema/ HTTP/1.1\" 500 145", "module": "basehttp", "function": "log_message", "line": 213}
{"timestamp": "2025-08-12T14:05:05.068593", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T14:05:05.234074", "level": "ERROR", "logger": "django.server", "message": "\"GET /api/v1/schema/ HTTP/1.1\" 500 145", "module": "basehttp", "function": "log_message", "line": 213}
{"timestamp": "2025-08-12T14:15:26.552071", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T14:15:26.583287", "level": "ERROR", "logger": "django.server", "message": "\"GET /api/v1/schema/ HTTP/1.1\" 500 145", "module": "basehttp", "function": "log_message", "line": 213}
{"timestamp": "2025-08-12T14:15:31.153999", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T14:15:31.172159", "level": "ERROR", "logger": "django.server", "message": "\"GET /api/v1/schema/ HTTP/1.1\" 500 145", "module": "basehttp", "function": "log_message", "line": 213}
{"timestamp": "2025-08-12T16:40:32.220423", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T16:40:32.246875", "level": "ERROR", "logger": "django.server", "message": "\"GET /api/v1/schema/ HTTP/1.1\" 500 145", "module": "basehttp", "function": "log_message", "line": 213}
{"timestamp": "2025-08-12T16:47:47.305003", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T16:47:47.368567", "level": "ERROR", "logger": "django.server", "message": "\"GET /api/v1/schema/ HTTP/1.1\" 500 145", "module": "basehttp", "function": "log_message", "line": 213}
{"timestamp": "2025-08-12T16:47:50.504309", "level": "ERROR", "logger": "django.request", "message": "Internal Server Error: /api/v1/schema/", "module": "log", "function": "log_response", "line": 253, "exception": "Traceback (most recent call last):\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 105, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 515, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 475, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 486, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Python312\\Lib\\site-packages\\rest_framework\\views.py\", line 512, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 84, in get\n    return self._get_schema_response(request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\views.py\", line 92, in _get_schema_response\n    data=generator.get_schema(request=request, public=self.serve_public),\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 285, in get_schema\n    paths=self.parse(request, public),\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\generators.py\", line 256, in parse\n    operation = view.schema.get_operation(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 112, in get_operation\n    operation['responses'] = self._get_response_bodies()\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1397, in _get_response_bodies\n    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1520, in _get_response_for_code\n    self._get_examples(serializer, direction, media_type, status_code, examples)\n  File \"C:\\Users\\IDAN\\AppData\\Roaming\\Python\\Python312\\site-packages\\drf_spectacular\\openapi.py\", line 1256, in _get_examples\n    if direction == 'response' and example.request_only:\n                                   ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'request_only'"}
{"timestamp": "2025-08-12T16:47:50.714248", "level": "ERROR", "logger": "django.server", "message": "\"GET /api/v1/schema/ HTTP/1.1\" 500 145", "module": "basehttp", "function": "log_message", "line": 213}
